### PR TITLE
Debug: Making sure that a package gets save even if he is already instal...

### LINKED ISSUE #104: Impossible to save a package if installed previously
If you want to save a package that you have already installed with ```bowerphp install jquery-address```.
It will fail because there is a check for that in [bowerphp.php line 100](https://github.com/Bee-Lab/bowerphp/blob/master/src/Bowerphp/Bowerphp.php#L100).

Not sure what the best approach is in this case ?

### PR DESCRIPTION
**Pull request by mikeSimonson**
...led

Previously if a package was already installed in the right version, saving it
in the bower.json was not possible because of an early exit.

Fix #104

### CODE REVIEW

File: src/Bowerphp/Bowerphp.php [hunk 1]
```diff
@@ -454,4 +448,15 @@ private function cachePackage(PackageInterface $package)
         $tmpFileName = $this->config->getCacheDir() . '/tmp/' . $package->getName();
         $this->filesystem->write($tmpFileName, $file);
     }
+
```
Comment (garak) [inline src/Bowerphp/Bowerphp.php]: phpdoc block missing

Comment (mikeSimonson) [inline src/Bowerphp/Bowerphp.php]: done

File: src/Bowerphp/Bowerphp.php [hunk 2]
```diff
@@ -454,4 +448,19 @@ private function cachePackage(PackageInterface $package)
...
+    /**
+     * @param PackageInterface $package
+     * @param bool $isDependency
+     */
+    private function updateBowerFile(PackageInterface $package, $isDependency=false)
```
Comment (garak) [inline src/Bowerphp/Bowerphp.php]: Sorry, I didn't notice this previously. Spacing here is not PSR-2 compatible.

**Comment by garak** [comment]
Thank you!
